ModelsToPrecache = {
-- BALKAN
"characters/models/tm_balkan/tm_balkan_variantf.vmdl",
"characters/models/tm_balkan/tm_balkan_variantg.vmdl",
"characters/models/tm_balkan/tm_balkan_varianth.vmdl",
"characters/models/tm_balkan/tm_balkan_varianti.vmdl",
"characters/models/tm_balkan/tm_balkan_variantj.vmdl",
"characters/models/tm_balkan/tm_balkan_variantk.vmdl",
"characters/models/tm_balkan/tm_balkan_variantl.vmdl",
-- JUMPSUIT
"characters/models/tm_jumpsuit/tm_jumpsuit_varianta.vmdl",
"characters/models/tm_jumpsuit/tm_jumpsuit_variantb.vmdl",
"characters/models/tm_jumpsuit/tm_jumpsuit_variantc.vmdl",
-- JUNGLERAIDER
"characters/models/tm_jungle_raider/tm_jungle_raider_varianta.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variantb.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variantb2.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variantc.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variantd.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variante.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variantf.vmdl",
"characters/models/tm_jungle_raider/tm_jungle_raider_variantf2.vmdl",
-- LEET
"characters/models/tm_leet/tm_leet_varianta.vmdl",
"characters/models/tm_leet/tm_leet_variantb.vmdl",
"characters/models/tm_leet/tm_leet_variantc.vmdl",
"characters/models/tm_leet/tm_leet_variantd.vmdl",
"characters/models/tm_leet/tm_leet_variante.vmdl",
"characters/models/tm_leet/tm_leet_variantf.vmdl",
"characters/models/tm_leet/tm_leet_variantg.vmdl",
"characters/models/tm_leet/tm_leet_varianth.vmdl",
"characters/models/tm_leet/tm_leet_varianti.vmdl",
"characters/models/tm_leet/tm_leet_variantj.vmdl",
"characters/models/tm_leet/tm_leet_variantk.vmdl",
-- PHOENIX
"characters/models/tm_phoenix/tm_phoenix.vmdl",
"characters/models/tm_phoenix/tm_phoenix_varianta.vmdl",
"characters/models/tm_phoenix/tm_phoenix_variantb.vmdl",
"characters/models/tm_phoenix/tm_phoenix_variantc.vmdl",
"characters/models/tm_phoenix/tm_phoenix_variantd.vmdl",
"characters/models/tm_phoenix/tm_phoenix_variantf.vmdl",
"characters/models/tm_phoenix/tm_phoenix_variantg.vmdl",
"characters/models/tm_phoenix/tm_phoenix_varianth.vmdl",
"characters/models/tm_phoenix/tm_phoenix_varianti.vmdl",
-- PHOENIX HEAVY
"characters/models/tm_phoenix_heavy/tm_phoenix_heavy.vmdl",
-- PROFESSIONAL
"characters/models/tm_professional/tm_professional_varf.vmdl",
"characters/models/tm_professional/tm_professional_varf1.vmdl",
"characters/models/tm_professional/tm_professional_varf2.vmdl",
"characters/models/tm_professional/tm_professional_varf3.vmdl",
"characters/models/tm_professional/tm_professional_varf4.vmdl",
"characters/models/tm_professional/tm_professional_varf5.vmdl",
"characters/models/tm_professional/tm_professional_varg.vmdl",
"characters/models/tm_professional/tm_professional_varh.vmdl",
"characters/models/tm_professional/tm_professional_vari.vmdl",
"characters/models/tm_professional/tm_professional_varj.vmdl",
-- SWAT
"characters/models/ctm_swat/ctm_swat_variante.vmdl",
"characters/models/ctm_swat/ctm_swat_variantf.vmdl",
"characters/models/ctm_swat/ctm_swat_varianth.vmdl",
"characters/models/ctm_swat/ctm_swat_varianti.vmdl",
"characters/models/ctm_swat/ctm_swat_variantj.vmdl",
"characters/models/ctm_swat/ctm_swat_variantk.vmdl",
-- ST6
"characters/models/ctm_st6/ctm_st6_variante.vmdl",
"characters/models/ctm_st6/ctm_st6_variantg.vmdl",
"characters/models/ctm_st6/ctm_st6_varianti.vmdl",
"characters/models/ctm_st6/ctm_st6_variantj.vmdl",
"characters/models/ctm_st6/ctm_st6_variantk.vmdl",
"characters/models/ctm_st6/ctm_st6_variantl.vmdl",
"characters/models/ctm_st6/ctm_st6_variantm.vmdl",
"characters/models/ctm_st6/ctm_st6_variantn.vmdl",
-- SAS
"characters/models/ctm_sas/ctm_sas.vmdl",
"characters/models/ctm_sas/ctm_sas_variantf.vmdl",
"characters/models/ctm_sas/ctm_sas_variantg.vmdl",
--CTM_HEAVY
"characters/models/ctm_heavy/ctm_heavy.vmdl",
--GENDARMERIE
"characters/models/ctm_gendarmerie/ctm_gendarmerie_varianta.vmdl",
"characters/models/ctm_gendarmerie/ctm_gendarmerie_variantb.vmdl",
"characters/models/ctm_gendarmerie/ctm_gendarmerie_variantc.vmdl",
"characters/models/ctm_gendarmerie/ctm_gendarmerie_variantd.vmdl",
"characters/models/ctm_gendarmerie/ctm_gendarmerie_variante.vmdl",
--FBI
"characters/models/ctm_fbi/ctm_fbi.vmdl",
"characters/models/ctm_fbi/ctm_fbi_varianta.vmdl",
"characters/models/ctm_fbi/ctm_fbi_variantb.vmdl",
"characters/models/ctm_fbi/ctm_fbi_variantc.vmdl",
"characters/models/ctm_fbi/ctm_fbi_variantd.vmdl",
"characters/models/ctm_fbi/ctm_fbi_variante.vmdl",
"characters/models/ctm_fbi/ctm_fbi_variantf.vmdl",
"characters/models/ctm_fbi/ctm_fbi_variantg.vmdl",
"characters/models/ctm_fbi/ctm_fbi_varianth.vmdl",
--DIVER
"characters/models/ctm_diver/ctm_diver_varianta.vmdl",
"characters/models/ctm_diver/ctm_diver_variantb.vmdl",
"characters/models/ctm_diver/ctm_diver_variantc.vmdl"
}
